from MemoryAutoScaling.Models.Statistical.StatisticalModel import StatisticalModel
from MemoryAutoScaling.Models.Statistical.TraceAR import TraceAR
from MemoryAutoScaling.Models.Statistical.TraceARIMA import TraceARIMA
from MemoryAutoScaling.Models.Statistical.TraceVARMA import TraceVARMA
